import assert from 'node:assert/strict';
import { createAsyncSessionPersistence } from '../src/db/asyncSessionPersistence.mjs';
function gate() { let resolve, reject; const promise = new Promise((a,b) => { resolve=a; reject=b; }); return { promise, resolve, reject }; }
const tick = () => new Promise(resolve => setImmediate(resolve));
const writes = [], errors = [];
const saves = createAsyncSessionPersistence({ flush: () => { const write=gate(); writes.push(write); return write.promise; }, onError: e => errors.push(e) });
const first=saves.enqueue('a');
assert.equal(first.status,'pending');
await tick(); assert.equal(writes.length,1);
let last;
for(let i=0;i<20;i++) last=saves.enqueue('a');
const other=saves.enqueue('b');
assert.equal(writes.length,1,'new mutations coalesce while a transaction is blocked');
writes[0].resolve(); await tick();
assert.equal(writes.length,2);
assert.equal(saves.status('a').saved_version,first.requested_version,'a snapshot cannot acknowledge mutations accepted after it started');
assert.equal(saves.status('a').status,'pending');
assert.equal(saves.status('b').saved_version,0);
writes[1].resolve(); await saves.drain();
assert.equal(saves.status('a').saved_version,last.requested_version);
assert.equal(saves.status('b').saved_version,other.requested_version);
assert.equal(saves.status('a').status,'saved');
const failed=saves.enqueue('a'); await tick();
saves.enqueue('b');
writes[2].reject(new Error('database down')); await saves.drain();
assert.equal(errors.length,1);
assert.equal(saves.status('a').status,'failed');
assert.equal(saves.status('b').status,'failed');
assert.ok(saves.status('a').saved_version<failed.requested_version);
assert.equal(saves.retry('a').status,'pending'); await tick();
assert.equal(saves.status('b').status,'failed','retry one session does not silently acknowledge another');
writes[3].resolve(); await saves.drain();
assert.equal(saves.status('a').status,'saved');
saves.retry('b'); await tick(); writes[4].resolve(); await saves.drain();
assert.equal(saves.status('b').status,'saved');
const memoryOnly=createAsyncSessionPersistence({enabled:()=>false,flush:()=>{throw new Error('must not write')}});
assert.equal(memoryOnly.enqueue('a').status,'saved');
assert.notEqual(memoryOnly.status('a').epoch,first.epoch,'restart epochs distinguish lost in-memory receipts');
console.log('Async saves: nonblocking enqueue, coalescing, snapshot watermarks, failure and retry isolation PASS');
