import assert from 'node:assert/strict';
import { createGenerationTasks } from '../src/agent/generationTasks.mjs';
const deferred = () => { let resolve, reject; const promise = new Promise((a,b) => {resolve=a;reject=b;});return {promise,resolve,reject}; };
const model = deferred(), commit = deferred();
const jobs = createGenerationTasks({waitMs: 5});
let calls = 0;
const work = async () => { calls++; const result = await model.promise; await commit.promise; return result; };
assert.equal((await jobs.poll('same', work)).kind, 'pending');
assert.equal((await jobs.poll('same', work)).kind, 'pending');
model.resolve({pending_id:'one'});
assert.equal((await jobs.poll('same', work)).kind, 'pending', '202 until durable commit, not just model completion');
commit.resolve();
const completed = await jobs.poll('same', work);
assert.deepEqual(completed, {kind:'done',value:{pending_id:'one'}});
assert.equal(calls,1,'polls and lost original connection never repeat generation');
const failure = deferred();
assert.equal((await jobs.poll('error',()=>failure.promise)).kind,'pending');
failure.reject(new Error('commit unavailable'));
await Promise.resolve();
const failed=await jobs.poll('error',()=>assert.fail('must deliver original failure'));
assert.equal(failed.kind,'failed');assert.equal(failed.error.message,'commit unavailable');
const bounded=createGenerationTasks({waitMs:1,maxEntries:1});
assert.equal((await bounded.poll('a',()=>new Promise(()=>{}))).kind,'pending');
assert.equal((await bounded.poll('b',()=>assert.fail('must not start beyond limit'))).kind,'busy');
console.log('Generation tasks: bounded polling, one completion, durable commit gate, detached errors PASS');
