const TOOL_NAMES = Object.freeze(['ask_player_choice', 'finish_story']);
const SENSITIVE_KEY_PATTERN = /^(password|token|access[_-]?token|secret|api[_-]?key|app[_-]?key|authorization|cookie|headers?)$/i;
class ToolValidationError extends Error { constructor(code, message) { super(message); this.name = 'ToolValidationError'; this.code = code; } }
const fail = (code, message) => { throw new ToolValidationError(code, message); };
const clone = (value) => value === undefined ? undefined : JSON.parse(JSON.stringify(value));
const deepFreeze = (value) => { if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value; Object.freeze(value); for (const entry of Object.values(value)) deepFreeze(entry); return value; };
const isSensitiveKey = (key) => { const normalized = key.replace(/[-_\s]/g, '').toLowerCase(); return SENSITIVE_KEY_PATTERN.test(key) || ['password', 'token', 'accesstoken', 'secret', 'apikey', 'appkey', 'authorization', 'cookie', 'headers', 'header'].includes(normalized); };
const assertFiniteJsonObject = (value, label) => { if (!value || typeof value !== 'object' || Array.isArray(value)) fail('invalid_input', `${label} must be a finite JSON object`); let json; try { json = JSON.parse(JSON.stringify(value)); } catch { fail('invalid_input', `${label} must be a finite JSON object`); } if (!json || typeof json !== 'object' || Array.isArray(json)) fail('invalid_input', `${label} must be a finite JSON object`); return json; };
const scanSensitiveKeys = (value, path = 'value') => { if (!value || typeof value !== 'object') return; if (Array.isArray(value)) { value.forEach((item, index) => scanSensitiveKeys(item, `${path}[${index}]`)); return; } for (const [key, child] of Object.entries(value)) { if (isSensitiveKey(key)) fail('invalid_input', `sensitive key rejected at ${path}.${key}`); scanSensitiveKeys(child, `${path}.${key}`); } };
const nonEmptyString = (value, label, code = 'invalid_tool_call') => { if (typeof value !== 'string' || !value.trim()) fail(code, `${label} must be a non-empty string`); return value; };
function normalizeAskPlayerChoice(arguments_) { const json = assertFiniteJsonObject(arguments_, 'ask_player_choice arguments'); scanSensitiveKeys(json, 'ask_player_choice_arguments'); const allowed = new Set(['question', 'options', 'allow_free_text', 'choice_id']); for (const key of Object.keys(json)) if (!allowed.has(key)) fail('invalid_tool_call', `ask_player_choice unknown field '${key}'`); const question = nonEmptyString(json.question, 'question'); if (!Array.isArray(json.options) || json.options.length < 2 || json.options.length > 6) fail('invalid_tool_call', 'ask_player_choice options must contain 2 to 6 items'); const seen = new Set(); const options = json.options.map((option, index) => { if (!option || typeof option !== 'object' || Array.isArray(option)) fail('invalid_tool_call', `ask_player_choice option ${index} must be an object`); const optionAllowed = new Set(['id', 'label', 'text', 'description']); for (const key of Object.keys(option)) if (!optionAllowed.has(key)) fail('invalid_tool_call', `ask_player_choice option ${index} unknown field '${key}'`); const id = nonEmptyString(option.id, `options[${index}].id`); if (seen.has(id)) fail('invalid_tool_call', 'ask_player_choice option id must be unique'); seen.add(id); const label = typeof option.label === 'string' && option.label.trim() ? option.label : option.text; if (typeof label !== 'string' || !label.trim()) fail('invalid_tool_call', `ask_player_choice option ${index} requires non-empty label/text`); const normalized = { id, label }; if (typeof option.description === 'string' && option.description.trim()) normalized.description = option.description; return normalized; }); const out = { question, options, allow_free_text: json.allow_free_text === undefined ? true : json.allow_free_text }; if (typeof out.allow_free_text !== 'boolean') fail('invalid_tool_call', 'allow_free_text must be boolean'); if (json.choice_id !== undefined) out.choice_id = nonEmptyString(json.choice_id, 'choice_id'); return clone(out); }
function normalizeFinishStory(arguments_) { const json = assertFiniteJsonObject(arguments_, 'finish_story arguments'); scanSensitiveKeys(json, 'finish_story_arguments'); const allowed = new Set(['summary', 'ending', 'original_difference', 'key_choices', 'character_outcomes', 'ending_key']); for (const key of Object.keys(json)) if (!allowed.has(key)) fail('invalid_tool_call', `finish_story unknown field '${key}'`); const summary = nonEmptyString(json.summary, 'summary'); const ending = nonEmptyString(json.ending, 'ending'); const original_difference = nonEmptyString(json.original_difference, 'original_difference'); if (!Array.isArray(json.key_choices) || json.key_choices.length < 1 || json.key_choices.length > 20) fail('invalid_tool_call', 'key_choices must contain 1 to 20 items'); const key_choices = json.key_choices.map((choice, index) => nonEmptyString(choice, `key_choices[${index}]`)); if (!Array.isArray(json.character_outcomes) || json.character_outcomes.length < 1 || json.character_outcomes.length > 20) fail('invalid_tool_call', 'character_outcomes must contain 1 to 20 items'); const character_outcomes = json.character_outcomes.map((item, index) => { if (!item || typeof item !== 'object' || Array.isArray(item)) fail('invalid_tool_call', `character_outcomes[${index}] must be an object`); const outcomeAllowed = new Set(['character', 'fate', 'change']); for (const key of Object.keys(item)) if (!outcomeAllowed.has(key)) fail('invalid_tool_call', `character_outcomes[${index}] unknown field '${key}'`); const out = { character: nonEmptyString(item.character, `character_outcomes[${index}].character`), fate: nonEmptyString(item.fate, `character_outcomes[${index}].fate`) }; if (typeof item.change === 'string' && item.change.trim()) out.change = item.change; return out; }); const out = { summary, ending, original_difference, key_choices, character_outcomes }; if (json.ending_key !== undefined) out.ending_key = nonEmptyString(json.ending_key, 'ending_key'); return clone(out); }
const TOOL_DEFINITIONS = deepFreeze([
  { type: 'function', function: { name: 'ask_player_choice', description: 'Ask the player to choose one of several options.', parameters: { type: 'object', additionalProperties: false, required: ['question', 'options'], properties: { question: { type: 'string', minLength: 1 }, options: { type: 'array', minItems: 2, maxItems: 6, items: { type: 'object', additionalProperties: false, required: ['id', 'label'], properties: { id: { type: 'string', minLength: 1 }, label: { type: 'string', minLength: 1 }, text: { type: 'string', minLength: 1 }, description: { type: 'string', minLength: 1 } } } }, allow_free_text: { type: 'boolean' }, choice_id: { type: 'string', minLength: 1 } } } } },
  { type: 'function', function: { name: 'finish_story', description: 'Finish the story with a summary and ending metadata.', parameters: { type: 'object', additionalProperties: false, required: ['summary', 'ending', 'original_difference', 'key_choices', 'character_outcomes'], properties: { summary: { type: 'string', minLength: 1 }, ending: { type: 'string', minLength: 1 }, original_difference: { type: 'string', minLength: 1 }, key_choices: { type: 'array', minItems: 1, maxItems: 20, items: { type: 'string', minLength: 1 } }, character_outcomes: { type: 'array', minItems: 1, maxItems: 20, items: { type: 'object', additionalProperties: false, required: ['character', 'fate'], properties: { character: { type: 'string', minLength: 1 }, fate: { type: 'string', minLength: 1 }, change: { type: 'string', minLength: 1 } } } }, ending_key: { type: 'string', minLength: 1 } } } } },
]);
const normalizeToolCallName = (name) => { if (typeof name !== 'string' || !TOOL_NAMES.includes(name)) fail('invalid_tool_call', 'unknown tool call'); return name; };
const normalizeToolCallId = (call) => { const id = call && typeof call === 'object' ? (call.tool_call_id ?? call.id) : undefined; if (typeof id === 'string' && id.trim()) return id; fail('invalid_tool_call', 'tool_call_id required'); };
export function validateAskPlayerChoice(arguments_) { return normalizeAskPlayerChoice(arguments_); }
export function validateFinishStory(arguments_) { return normalizeFinishStory(arguments_); }
export function createToolRegistry() { return { definitions: clone(TOOL_DEFINITIONS), executeToolCall }; }
export function executeToolCall({ name, arguments: args, session_uuid, turn_id, base_revision, tool_call_id }) { if (session_uuid !== undefined && typeof session_uuid !== 'string') fail('invalid_input', 'session_uuid must be a UUID string'); if (turn_id !== undefined && typeof turn_id !== 'string') fail('invalid_input', 'turn_id must be a UUID string'); if (base_revision !== undefined && (!Number.isInteger(base_revision) || base_revision < 0)) fail('invalid_input', 'base_revision must be a non-negative integer'); const normalizedName = normalizeToolCallName(name); const normalizedId = typeof tool_call_id === 'string' && tool_call_id.trim() ? tool_call_id : normalizeToolCallId({ id: tool_call_id }); const normalizedArgs = normalizedName === 'ask_player_choice' ? validateAskPlayerChoice(args) : validateFinishStory(args); return normalizedName === 'ask_player_choice' ? { tool_call_id: normalizedId, name: normalizedName, kind: 'choice_required', session_uuid, turn_id, base_revision, requires_player: true, terminal: false, payload: normalizedArgs } : { tool_call_id: normalizedId, name: normalizedName, kind: 'story_finished', session_uuid, turn_id, base_revision, requires_player: false, terminal: true, payload: normalizedArgs }; }
deepFreeze(TOOL_NAMES);
export { TOOL_DEFINITIONS, TOOL_NAMES, ToolValidationError };
